### ISSUE TITLE
Proposed Redesign and Rename

### ISSUE THREAD

**Issue by Pr0x1m4** [helium96/ThymeTable#3]
Proposing to redesign to the following and rename the Skedulr app to ThymeTable
![thymetable-logo](https://cloud.githubusercontent.com/assets/4820517/12397218/e385d70e-bdd9-11e5-9ed6-90e6875f516a.png)
![thymetable-mockups](https://cloud.githubusercontent.com/assets/4820517/12397219/e38ed9b2-bdd9-11e5-9aa0-3ae6c0047722.png)

**Comment by Pr0x1m4** [comment]
![thymetable-logo-without-words](https://cloud.githubusercontent.com/assets/4820517/12433154/713009e6-becd-11e5-904d-4ae172619d78.png)

**Comment by Pr0x1m4** [comment]
Font Used: [Raleway](http://www.fontsquirrel.com/fonts/raleway)

**Comment by Pr0x1m4** [comment]
mobile app logo
![thymetable-logo-app](https://cloud.githubusercontent.com/assets/4820517/12538145/aeb53464-c29f-11e5-957e-b75046653377.png)

**Comment by helium96** [comment]
Remember that a Splash is needed as well @Pr0x1m4

**Comment by Pr0x1m4** [comment]
Generate Splash screen for platforms with `ionic resource --splash`, here's the 1200x1200 image needed, place in resources folder and run command

See this link for greater detail [Ionic Splash Screen Generator](http://blog.ionic.io/automating-icons-and-splash-screens/)
![splash](https://cloud.githubusercontent.com/assets/4820517/12635730/71951010-c554-11e5-9043-96cc8390f613.png)
